import streamlit as st
import boto3
from botocore.config import Config
import time
import json

# -----------------------------
# Config from Secrets (with fallback)
# -----------------------------
RATE_LIMIT = st.secrets.get("rate_limit", {}).get("max_requests", 6)
TIME_WINDOW = st.secrets.get("rate_limit", {}).get("time_window_seconds", 60)
BEDROCK_REGION = st.secrets.get("aws", {}).get("region", "us-east-1")

# -----------------------------
# Rate Limiting Setup (Per User)
# -----------------------------
def check_rate_limit():
    if "requests" not in st.session_state:
        st.session_state["requests"] = []

    now = time.time()
    st.session_state["requests"] = [
        ts for ts in st.session_state["requests"] if now - ts < TIME_WINDOW
    ]

    if len(st.session_state["requests"]) >= RATE_LIMIT:
        return False

    st.session_state["requests"].append(now)
    return True

# -----------------------------
# Bedrock Client Setup
# -----------------------------
bedrock_client = boto3.client(
    "bedrock-runtime",
    region_name=BEDROCK_REGION,
    config=Config(retries={"max_attempts": 3}),
)

# -----------------------------
# Streamlit App Styling
# -----------------------------
st.set_page_config(
    page_title="AI Slogan Generator",
    page_icon="🤖",
    layout="centered",
)

# Custom CSS for gradients, fonts, and button styling
st.markdown(
    """
    <style>
    /* Background gradient */
    .stApp {
        background: linear-gradient(135deg, #ff7eb3 0%, #ff758c 50%, #ffb347 100%);
        color: #fff;
        font-family: 'Segoe UI', sans-serif;
    }

    /* Title styling */
    .title {
        font-size: 3rem;
        font-weight: bold;
        text-align: center;
        margin-bottom: 0.5rem;
        text-shadow: 2px 2px 5px rgba(0,0,0,0.3);
    }

    /* Subtitle / Markdown */
    .subtitle {
        font-size: 1.25rem;
        text-align: center;
        margin-bottom: 2rem;
        color: #f0f0f0;
    }

    /* Input box */
    div[data-baseweb="input"] > input {
        border-radius: 12px;
        padding: 12px;
        font-size: 1rem;
        border: 2px solid #fff;
        background: rgba(255,255,255,0.1);
        color: #fff;
    }

    /* Button styling */
    div.stButton > button {
        background: linear-gradient(90deg, #00c6ff 0%, #0072ff 100%);
        color: #fff;
        font-size: 1rem;
        font-weight: bold;
        padding: 10px 25px;
        border-radius: 12px;
        border: none;
        transition: 0.3s;
    }

    div.stButton > button:hover {
        background: linear-gradient(90deg, #0072ff 0%, #00c6ff 100%);
        transform: scale(1.05);
    }

    /* Success message */
    .stSuccess {
        background-color: rgba(0,255,128,0.2);
        border-left: 5px solid #00ff85;
        padding: 10px;
        border-radius: 8px;
    }

    /* Error message */
    .stError {
        background-color: rgba(255,0,64,0.2);
        border-left: 5px solid #ff0040;
        padding: 10px;
        border-radius: 8px;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# -----------------------------
# App Content
# -----------------------------
st.markdown('<div class="title">AI Slogan Generator</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="subtitle">Enter a product, idea, or service and get a catchy slogan generated by Amazon Bedrock!</div>',
    unsafe_allow_html=True,
)

prompt = st.text_input("Enter your product/idea:")

if st.button("Generate Slogan"):
    if not prompt:
        st.error("Please enter a prompt!")
    elif not check_rate_limit():
        st.error(
            f"Rate limit exceeded. Max {RATE_LIMIT} requests per {TIME_WINDOW} sec."
        )
    else:
        try:
            response = bedrock_client.invoke_model(
                modelId="amazon.nova-lite-v1:0",
                contentType="application/json",
                body=json.dumps(
                    {
                        "messages": [
                            {
                                "role": "user",
                                "content": [
                                    {"text": f"Generate a catchy slogan for: {prompt}"}
                                ],
                            }
                        ],
                        "inferenceConfig": {"maxTokens": 60, "temperature": 0.8},
                    }
                ),
            )

            result_str = response["body"].read().decode("utf-8")
            result_json = json.loads(result_str)

            slogan = (
                (
                    result_json.get("output", {})
                    .get("message", {})
                    .get("content", [{}])[0]
                    .get("text", "No slogan generated")
                )
                .strip('"')
                .strip()
            )

            st.success(f"Slogan generated: **{slogan}**")

        except Exception as e:
            st.error(f"Error generating slogan: {e}")
