import streamlit as st
import boto3
from botocore.config import Config
import time
import json

# -----------------------------
# Config from Secrets (with fallback)
# -----------------------------
RATE_LIMIT = st.secrets.get("rate_limit", {}).get("max_requests", 6)
TIME_WINDOW = st.secrets.get("rate_limit", {}).get("time_window_seconds", 60)
BEDROCK_REGION = st.secrets.get("aws", {}).get("region", "us-east-1")

# -----------------------------
# Rate Limiting Setup
# -----------------------------
def check_rate_limit():
    if "requests" not in st.session_state:
        st.session_state["requests"] = []

    now = time.time()
    st.session_state["requests"] = [
        ts for ts in st.session_state["requests"] if now - ts < TIME_WINDOW
    ]

    if len(st.session_state["requests"]) >= RATE_LIMIT:
        return False

    st.session_state["requests"].append(now)
    return True

# -----------------------------
# Bedrock Client Setup
# -----------------------------
bedrock_client = boto3.client(
    "bedrock-runtime",
    region_name=BEDROCK_REGION,
    config=Config(retries={"max_attempts": 3}),
)

# -----------------------------
# Streamlit Styling
# -----------------------------
st.set_page_config(
    page_title="AI Slogan Generator",
    layout="centered",
)

st.markdown(
    """
    <style>
    .stApp {
        background: linear-gradient(135deg, #00c6ff 0%, #0072ff 50%, #ffb347 100%);
        font-family: 'Segoe UI', sans-serif;
        color: #fff;
    }
    .title {
        font-size: 3rem;
        font-weight: bold;
        text-align: center;
        margin-bottom: 0.5rem;
        text-shadow: 2px 2px 5px rgba(0,0,0,0.3);
    }
    .subtitle {
        font-size: 1.25rem;
        text-align: center;
        margin-bottom: 2rem;
        color: #f0f0f0;
    }
    div[data-baseweb="input"] > input {
        border-radius: 12px;
        padding: 12px;
        font-size: 1rem;
        border: 2px solid #fff;
        background: rgba(255,255,255,0.2);
        color: #fff;
    }
    div.stButton > button {
        display: block;
        margin: 0 auto;
        background: linear-gradient(90deg, #ff8c00 0%, #ff6600 100%);
        color: #fff;
        font-size: 1.1rem;
        font-weight: bold;
        padding: 12px 30px;
        border-radius: 15px;
        border: none;
        transition: 0.3s;
    }
    div.stButton > button:hover {
        background: linear-gradient(90deg, #ff6600 0%, #ff8c00 100%);
        transform: scale(1.05);
    }
    .result-box {
        background: rgba(0,0,0,0.6);
        border-left: 5px solid #00ff85;
        border-radius: 15px;
        padding: 20px;
        margin-top: 20px;
        font-size: 1.6rem;
        font-weight: bold;
        text-align: center;
        color: #fff;
        box-shadow: 3px 3px 15px rgba(0,0,0,0.4);
        opacity: 0;
        animation: fadeIn 1s forwards;
    }
    @keyframes fadeIn { to { opacity: 1; } }
    .stError {
        background-color: rgba(255,0,0,0.2);
        border-left: 5px solid #ff0000;
        padding: 10px;
        border-radius: 8px;
        color: #fff;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# -----------------------------
# App Content
# -----------------------------
st.markdown('<div class="title">AI Slogan Generator</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="subtitle">Enter a product and an optional theme to get a catchy slogan generated by AI!</div>',
    unsafe_allow_html=True,
)

# New Inputs
product = st.text_input("Enter your product/idea:")
theme = st.text_input("Optional: Enter the theme or style for the slogan:")

if st.button("Generate Slogan"):
    if not product:
        st.error("Please enter a product or idea!")
    elif not check_rate_limit():
        st.error(
            f"Rate limit exceeded. Max {RATE_LIMIT} requests per {TIME_WINDOW} sec."
        )
    else:
        try:
            # Update prompt to include product and theme
            full_prompt = f"Generate a catchy slogan for the product/idea: '{product}'"
            if theme:
                full_prompt += f" with the theme/style: '{theme}'"

            response = bedrock_client.invoke_model(
                modelId="amazon.nova-lite-v1:0",
                contentType="application/json",
                body=json.dumps(
                    {
                        "messages": [
                            {"role": "user", "content": [{"text": full_prompt}]}
                        ],
                        "inferenceConfig": {"maxTokens": 60, "temperature": 0.8},
                    }
                ),
            )

            result_str = response["body"].read().decode("utf-8")
            result_json = json.loads(result_str)

            slogan = (
                (
                    result_json.get("output", {})
                    .get("message", {})
                    .get("content", [{}])[0]
                    .get("text", "No slogan generated")
                )
                .strip('"')
                .strip()
            )

            st.markdown(f'<div class="result-box">{slogan}</div>', unsafe_allow_html=True)

        except Exception as e:
            st.error(f"Error generating slogan: {e}")
